# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - 3.7

# Command to run tests, e.g. python setup.py test
install:
- pip install pipenv
- pipenv install xlrd
- pipenv install --system --deploy --ignore-pipfile

stages:
  - test
  - name: answers
    if: branch = master

env:
  -AWS_ACCESS_KEY_ID= AKIAQN6XZ5ZGO6GZ6WO4
  -AWS_SECRET_ACCESS_KEY= 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
  -CSCI_SALT=3f87b3a5b7e48ba408964366a7194789249d4ed33b962a9e5d76c5d6122237bc
  -region = us-east-1
  -output = json


jobs:
  include:
    - stage: test
      script: pytest -v
      install:
        - pipenv install --dev --ignore-pipfile --deploy
      before_script: # code coverage tool
         - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
         - chmod +x ./cc-test-reporter
         - ./cc-test-reporter before-build
      script: pytest --cov-report xml --cov-report term
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    - stage: answers
      script:
      # Before running, get the data from s3 using the secret
      # credentials entered at https://travis-ci.com/csci-e-29/YOUR_PSET_REPO_NAME/settings
      # DO NOT commit these variables to git.
      - aws configure set aws_access_key_id AKIAQN6XZ5ZGO6GZ6WO4
      - aws configure set aws_secret_access_key ok4qCdAOB79hd8SoCG/Hu9odnNgj8cx/Kzdp1NlZ
      - make data
      - python3 -m pset_1
