version: '3'
services:
  app:
    environment:
      - AWS_ACCESS_KEY_ID = 'AKIAQN6XZ5ZGPGNGVCDQ'
      - AWS_SECRET_ACCESS_KEY = '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'
    build: 
      context: .

    volumes:
      - .:/app